import { useMemo, useState } from 'react'
import fallbackImage from './assets/hero.png'
import './App.css'

const categories = [{ id: 'all', label: 'All places', icon: '✦' }, { id: 'landmark', label: 'Landmarks', icon: '⌂' }, { id: 'nature', label: 'Nature', icon: '◒' }, { id: 'culture', label: 'Culture', icon: '✺' }, { id: 'food', label: 'Food & stay', icon: '♨' }]
const makePlace = (id, name, type, category, distance, time, rating, color, x, y, description, image) => ({ id, name, type, category, distance, time, rating, color, x, y, description, image })
const images = {
  fort: 'https://images.unsplash.com/photo-1592639296346-560c37a0f711?auto=format&fit=crop&w=500&q=80', palace: 'https://images.unsplash.com/photo-1605649487212-47bdab064df7?auto=format&fit=crop&w=500&q=80', hill: 'https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=500&q=80', temple: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtv_jnT0JuWduKo8OsE-D4c2qomq3LEywfbskZAmoEvA&s=10', food: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=500&q=80', sea: 'https://images.unsplash.com/photo-1595658658481-d53d3f999875?auto=format&fit=crop&w=500&q=80', fort2: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=500&q=80', palace2: 'https://www.bing.com/images/search?view=detailV2&ccid=ToT9gJZw&id=88F23EBD6BBA7B6565A6B0545C0F6AB3712FC8C7&thid=OIP.ToT9gJZwKupZpiiX0sPxiQHaEo&mediaurl=https%3a%2f%2fim.whatshot.in%2fimg%2f2020%2fAug%2fshutterstock-1343964503-cropped-1560157575-1597129381.jpg%3fwp%3d1&exph=3240&expw=5184&q=dadadu+shet+ganapti&FORM=IRPRST&ck=35F27D1EEB38923B59DE6AA9539F55CE&selectedIndex=0&itb=0', hotel: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=500&q=80'
}
const cities = {
  pune: {
    name: 'Pune', region: 'Maharashtra, India', weather: '28°', conditions: 'Partly cloudy', tone: 'pune', places: [
      makePlace('shaniwar', 'Shaniwar Wada', 'culture', 'Historic', '1.2 km', '8 min', '4.4', '#ea7658', 43, 43, 'The storied heart of old Pune, best explored at sunset.', images.fort), makePlace('aga-khan', 'Aga Khan Palace', 'landmark', 'Landmark', '6.8 km', '24 min', '4.5', '#ec9f42', 70, 29, 'A peaceful landmark wrapped in gardens and history.', images.palace), makePlace('parvati', 'Parvati Hill', 'nature', 'Viewpoint', '3.4 km', '18 min', '4.6', '#55a795', 35, 67, 'A sunrise climb with the city spread below you.', images.hill), makePlace('sinhagad', 'Sinhagad Fort', 'nature', 'Fort & trail', '31 km', '1 hr 18 min', '4.8', '#528a75', 16, 76, 'Misty trails, dramatic views and hot kanda bhaji.', images.fort2), makePlace('dagdusheth', 'Dagdusheth Temple', 'culture', 'Temple', '1.8 km', '10 min', '4.7', '#d97c4b', 50, 53, 'An ornate, beloved temple in the old city lanes.', images.temple), makePlace('fc-road', 'FC Road Food Walk', 'food', 'Food & stay', '2.7 km', '14 min', '4.6', '#db7693', 38, 31, 'Cafes, bakeries and the city’s best quick bites.', images.food)
    ], hotels: [['The Fern Residency', 'Kharadi · 4.2 km away', '₹4,850', '4.6'], ['Blue Diamond Pune', 'Koregaon Park · 2.1 km away', '₹7,200', '4.8']]
  },
  mumbai: {
    name: 'Mumbai', region: 'Maharashtra, India', weather: '30°', conditions: 'Humid & bright', tone: 'mumbai', places: [
      makePlace('gateway', 'Gateway of India', 'landmark', 'Landmark', '2.4 km', '14 min', '4.7', '#e9a34d', 46, 30, 'Mumbai’s grand waterfront welcome and harbour views.', images.palace), makePlace('marine-drive', 'Marine Drive', 'nature', 'Viewpoint', '4.8 km', '22 min', '4.8', '#4c9a9b', 36, 65, 'A breezy promenade made for golden-hour walks.', images.sea), makePlace('elephanta', 'Elephanta Caves', 'culture', 'Heritage', '11 km', '1 hr 05 min', '4.5', '#c77d58', 78, 22, 'Rock-cut temples on a quiet island in the harbour.', images.temple), makePlace('bandra', 'Bandra Fort', 'nature', 'Sunset spot', '12 km', '38 min', '4.6', '#5a9b82', 16, 43, 'Sea breeze, old stone walls and a postcard skyline.', images.fort2), makePlace('thali', 'Fort Food Trail', 'food', 'Food & stay', '3.1 km', '17 min', '4.6', '#d7758e', 52, 48, 'A delicious crawl through iconic South Mumbai kitchens.', images.food)
    ], hotels: [['Abode Bombay', 'Colaba · 1.4 km away', '₹6,900', '4.7'], ['The St. Regis Mumbai', 'Lower Parel · 6.2 km away', '₹13,500', '4.8']]
  },
  jaipur: {
    name: 'Jaipur', region: 'Rajasthan, India', weather: '32°', conditions: 'Sunny', tone: 'jaipur', places: [
      makePlace('amber', 'Amber Fort', 'landmark', 'Landmark', '9.2 km', '28 min', '4.8', '#df9d46', 76, 25, 'A honey-coloured hilltop palace of courtyards and mirrors.', images.fort2), makePlace('hawa', 'Hawa Mahal', 'culture', 'Historic', '1.6 km', '9 min', '4.6', '#d87559', 45, 45, 'The iconic Palace of Winds in the heart of the Pink City.', images.palace2), makePlace('city-palace', 'City Palace', 'culture', 'Museum', '1.1 km', '7 min', '4.7', '#c66e83', 53, 40, 'Royal courtyards, galleries and a living palace complex.', images.palace), makePlace('jal-mahal', 'Jal Mahal', 'nature', 'Viewpoint', '5.8 km', '20 min', '4.5', '#5d9f96', 65, 63, 'A dreamy water palace framed by the Aravalli hills.', images.sea), makePlace('bazaar', 'Johari Bazaar', 'food', 'Shopping & food', '2.2 km', '12 min', '4.5', '#d5758a', 29, 58, 'Colourful lanes for block prints, bangles and kachori.', images.food)
    ], hotels: [['Samode Haveli', 'Gangapole · 2.8 km away', '₹9,800', '4.8'], ['Dera Amer Wilderness Camp', 'Delhi Road · 11 km away', '₹12,400', '4.9']]
  }
}

function App() {
  const [query, setQuery] = useState('Pune'); const [cityKey, setCityKey] = useState('pune'); const [category, setCategory] = useState('all'); const [view, setView] = useState('map'); const [selected, setSelected] = useState(null); const [favorites, setFavorites] = useState([]); const [itinerary, setItinerary] = useState([]); const [dark, setDark] = useState(false); const [menu, setMenu] = useState(false); const [savedOnly, setSavedOnly] = useState(false)
  const city = cities[cityKey]; const filtered = useMemo(() => city.places.filter((place) => (category === 'all' || place.type === category) && (!savedOnly || favorites.includes(place.id))), [city, category, favorites, savedOnly]); const selectedPlace = city.places.find((place) => place.id === selected)
  const searchCity = (event) => { event.preventDefault(); const found = Object.keys(cities).find((key) => key.includes(query.trim().toLowerCase()) || cities[key].name.toLowerCase().includes(query.trim().toLowerCase())); if (found) { setCityKey(found); setCategory('all'); setSelected(null) } }
  const toggle = (setter, id) => setter((items) => items.includes(id) ? items.filter((item) => item !== id) : [...items, id])
  return <div className={`app ${dark ? 'dark' : ''}`}>
    <header className="topbar"><a className="brand" href="#top"><span className="brand-mark">✦</span><span>trip<span>explorer</span></span></a><nav className={menu ? 'nav open' : 'nav'}><a className="active" href="#explore" onClick={() => { setSavedOnly(false); setCategory('all'); setView('map') }}>Explore</a><a href="#stays">Stays</a><a href="#food" onClick={(event) => { event.preventDefault(); setSavedOnly(false); setCategory('food'); setView('list'); document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' }) }}>Food & drink</a><a href="#saved" onClick={(event) => { event.preventDefault(); setSavedOnly(true); setCategory('all'); setView('list'); document.getElementById('explore')?.scrollIntoView({ behavior: 'smooth' }) }}>Saved <b>{favorites.length || ''}</b></a></nav><div className="header-actions"><button className="icon-button" onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? '☼' : '◐'}</button><button className="avatar" aria-label="Open profile">AR</button><button className="menu-button" onClick={() => setMenu(!menu)} aria-label="Toggle menu">☰</button></div></header>
    <main id="top"><section className="hero" id="explore"><div className="hero-copy"><p className="eyebrow"><span /> Your next good day out</p><h1>Make room for<br /><em>curiosity.</em></h1><p className="hero-sub">Discover the places, flavours and little detours that make a city feel like yours.</p></div><div className="hero-note"><span className="note-icon">↗</span><div><strong>Plan less. Wander more.</strong><small>Curated trips made for real life.</small></div></div><form className="search-bar" onSubmit={searchCity}><span className="icon">⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} aria-label="Search a city" placeholder="Where do you want to go?" /><span className="search-hint">Try Pune, Mumbai or Jaipur</span><button type="submit">Explore <span>→</span></button></form></section>
      <section className="content-shell"><div className="location-row"><div><p className="overline">Showing you around</p><h2>{city.name}<span>, {city.region}</span></h2></div><div className="weather"><span className="sun">☼</span><div><strong>{city.weather}</strong><small>{city.conditions}</small></div></div><div className="demo-badge"><span /> Demo data <button aria-label="About demo data">?</button></div></div>
        <div className="workspace"><aside className="sidebar"><div className="side-head"><div><p className="overline">A good place to start</p><h3>Explore {city.name}</h3></div><button className="filter-button" aria-label="Open filters">☷</button></div><div className="category-list">{categories.map((item) => <button key={item.id} className={category === item.id && !savedOnly ? 'category active' : 'category'} onClick={() => { setSavedOnly(false); setCategory(item.id) }}><span className="cat-icon">{item.icon}</span>{item.label}<span className="count">{item.id === 'all' ? city.places.length : city.places.filter((place) => place.type === item.id).length}</span></button>)}</div><div className="quick-card"><div className="spark">✦</div><div><strong>Make it a day</strong><p>We picked a relaxed route with {city.places.length} stops.</p><button onClick={() => setItinerary(city.places.slice(0, 4).map((place) => place.id))}>Build my itinerary <span>→</span></button></div></div><div className="side-meta"><span>◎ {filtered.length} places</span><span>◷ Updated just now</span></div></aside>
          <div className="main-panel"><div className="panel-toolbar"><div className="result-copy"><strong>{savedOnly ? 'Your saved places' : category === 'all' ? 'Popular around here' : categories.find((item) => item.id === category)?.label}</strong><span>{filtered.length} places to explore</span></div><div className="view-toggle"><button className={view === 'map' ? 'selected' : ''} onClick={() => setView('map')}>⌖ Map</button><button className={view === 'list' ? 'selected' : ''} onClick={() => setView('list')}>☷ List</button></div></div>{view === 'map' ? <Map city={city} places={filtered} selected={selected} onSelect={setSelected} /> : filtered.length ? <div className="list-view">{filtered.map((place) => <PlaceCard key={place.id} place={place} favorite={favorites.includes(place.id)} planned={itinerary.includes(place.id)} onFavorite={() => toggle(setFavorites, place.id)} onPlan={() => toggle(setItinerary, place.id)} onSelect={() => setSelected(place.id)} />)}</div> : <div className="empty-state"><strong>{savedOnly ? 'No saved places yet' : 'Nothing here yet'}</strong><p>{savedOnly ? 'Tap the heart on a place to keep it for later.' : 'Try another category or city.'}</p></div>}{view === 'map' && <div className="map-caption"><span className="live-dot" /><strong>Routes are simulated</strong><span>Based on typical weekday travel time</span><button onClick={() => setView('list')}>View all places <span>→</span></button></div>}</div></div>
        {selectedPlace && <div className="detail-panel"><ImageWithFallback src={selectedPlace.image} alt="" /><div className="detail-content"><button className="close-detail" onClick={() => setSelected(null)} aria-label="Close details">×</button><p className="overline">{selectedPlace.category}</p><h3>{selectedPlace.name}</h3><p>{selectedPlace.description}</p><div className="detail-stats"><span>★ {selectedPlace.rating}</span><span>⌖ {selectedPlace.distance}</span><span>◷ {selectedPlace.time}</span></div><div className="detail-actions"><button className="primary-small" onClick={() => toggle(setItinerary, selectedPlace.id)}>{itinerary.includes(selectedPlace.id) ? 'Added to day' : 'Add to itinerary'}</button><button className="outline-small" onClick={() => toggle(setFavorites, selectedPlace.id)}>{favorites.includes(selectedPlace.id) ? '♥ Saved' : '♡ Save'}</button></div></div></div>}
        <section className="lower-grid" id="stays"><div className="section-heading"><div><p className="overline">Rest easy</p><h2>Stay somewhere lovely</h2></div><button className="text-button">See all stays <span>→</span></button></div><div className="hotel-grid">{city.hotels.map(([name, area, price, rating]) => <article className="hotel-card" key={name}><ImageWithFallback src={images.hotel} alt="" /><div className="hotel-info"><div className="hotel-top"><span className="hotel-type">Boutique stay</span><span>♡</span></div><h3>{name}</h3><p>{area}</p><div><strong>{price}</strong><span> / night</span><b>★ {rating}</b></div></div></article>)}</div></section>
        <section className="trip-summary"><div className="summary-intro"><p className="overline">Your day, sorted</p><h2>{itinerary.length ? `${itinerary.length} stops in your plan` : 'A little help planning?'}</h2><p>{itinerary.length ? 'A relaxed route with space for the unexpected.' : 'Save places as you explore and we’ll turn them into a route.'}</p></div><div className="summary-stats"><div><span>◷</span><strong>{itinerary.length ? `${Math.max(3, itinerary.length * 2)}h 20m` : '0h 00m'}</strong><small>estimated time</small></div><div><span>⌖</span><strong>{itinerary.length ? `${(itinerary.length * 3.2).toFixed(1)} km` : '—'}</strong><small>total distance</small></div><div><span>₹</span><strong>{itinerary.length ? `₹${itinerary.length * 290}` : '—'}</strong><small>approx. spend</small></div></div><button className="outline-small" onClick={() => setView('list')}>Open itinerary <span>→</span></button></section><footer><span>trip<span>explorer</span></span><span>Made for wandering · {city.name} edition</span><span><span className="live-dot" /> Simulated route & traffic data</span></footer></section></main></div>
}

function ImageWithFallback({ src, alt, onClick }) { return <img src={src} alt={alt} onClick={onClick} onError={(event) => { event.currentTarget.onerror = null; event.currentTarget.src = fallbackImage }} /> }
function Map({ city, places, selected, onSelect }) { return <div className={`map-view ${city.tone}`}><div className="map-label label-one">{city.name} centre</div><div className="map-label label-two">Old city</div><svg className="route route-one" viewBox="0 0 700 420" preserveAspectRatio="none"><path d="M80 320 C180 245 200 200 310 220 S450 160 510 80" /></svg><svg className="route route-two" viewBox="0 0 700 420" preserveAspectRatio="none"><path d="M165 375 C270 340 300 285 365 270 S540 235 600 205" /></svg>{places.map((place) => <button key={place.id} className={`map-pin ${selected === place.id ? 'selected' : ''}`} style={{ left: `${place.x}%`, top: `${place.y}%`, '--pin': place.color }} onClick={() => onSelect(place.id)} aria-label={`Show ${place.name}`}><span>•</span><small>{place.name}</small></button>)}<div className="map-tools"><button aria-label="Zoom in">+</button><button aria-label="Zoom out">−</button></div><div className="map-legend"><span><i /> Suggested route</span><span><i className="traffic" /> Moderate traffic</span></div></div> }
function PlaceCard({ place, favorite, planned, onFavorite, onPlan, onSelect }) { return <article className="place-card"><ImageWithFallback src={place.image} alt={place.name} onClick={onSelect} /><div className="place-info" onClick={onSelect}><div className="place-top"><span className="place-category">{place.category}</span><button className={favorite ? 'favorite saved' : 'favorite'} onClick={(event) => { event.stopPropagation(); onFavorite() }} aria-label="Save place">{favorite ? '♥' : '♡'}</button></div><h3>{place.name}</h3><p>{place.description}</p><div className="place-meta"><span>★ {place.rating}</span><span>⌖ {place.distance}</span><span>◷ {place.time}</span></div><button className={planned ? 'plan-button planned' : 'plan-button'} onClick={(event) => { event.stopPropagation(); onPlan() }}>{planned ? '✓ Planned' : '+ Add to day'}</button></div></article> }
export default App
